name: class_test
description: Allows structuring flutter tests using classes instead of functions to simplify polymorphism testing.
version: 1.0.0
author: Horoliuk Maksym <goroliuk.maksym@gmail.com>
homepage: https://github.com/gorolykmaxim/class_test

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1